#!/usr/bin/env python3
"""Render a TrueType font into the 1 bpp glyph tables declared in src/font.h.

The output is committed, so the firmware build needs neither the font file nor
this script. Example, from the firmware directory:

    python scripts/font2c.py /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf \
        22 font_body src/fonts/font_body.c
"""

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

# ASCII, Latin-1 supplement, and the few French characters that live outside it.
DEFAULT_CHARSET = (
    "".join(chr(c) for c in range(0x20, 0x7F))
    + "".join(chr(c) for c in range(0xA0, 0x100))
    + "ŒœŸ€’…"
)

BYTES_PER_LINE = 12


def render_glyph(font, char, height):
    """Return (advance, packed 1 bpp rows), or None for a zero-width character."""
    advance = round(font.getlength(char))
    if advance <= 0:
        return None
    if advance > 255:
        raise ValueError(f"U+{ord(char):04X} is {advance} px wide, font.h stores 8 bits")

    image = Image.new("1", (advance, height), 0)
    draw = ImageDraw.Draw(image)
    # Hinted monochrome rendering stays crisper than thresholded antialiasing.
    draw.fontmode = "1"
    draw.text((0, 0), char, font=font, fill=1, anchor="la")
    return advance, image.tobytes()


def format_bytes(data):
    lines = []
    for start in range(0, len(data), BYTES_PER_LINE):
        chunk = data[start : start + BYTES_PER_LINE]
        lines.append("\t" + " ".join(f"0x{byte:02x}," for byte in chunk))
    return "\n".join(lines)


def generate(ttf_path, size, name, charset):
    font = ImageFont.truetype(str(ttf_path), size)
    ascent, descent = font.getmetrics()
    height = ascent + descent
    if height > 255:
        raise ValueError(f"Line height is {height} px, font.h stores 8 bits")

    bitmaps = bytearray()
    glyphs = []
    for char in sorted(set(charset)):
        if ord(char) > 0xFFFF:
            raise ValueError(f"U+{ord(char):X} is outside the Basic Multilingual Plane")
        rendered = render_glyph(font, char, height)
        if rendered is None:
            continue
        advance, rows = rendered
        glyphs.append((ord(char), advance, len(bitmaps)))
        bitmaps += rows

    glyph_lines = "\n".join(
        f"\t{{ 0x{codepoint:04x}, {advance}, {offset} }}," for codepoint, advance, offset in glyphs
    )

    return f"""/*
 * Generated by scripts/font2c.py from {ttf_path.name} at {size} px.
 * Do not edit by hand, regenerate instead.
 */

#include <zephyr/sys/util.h>

#include "font.h"

static const uint8_t bitmaps[] = {{
{format_bytes(bitmaps)}
}};

static const struct font_glyph glyphs[] = {{
{glyph_lines}
}};

const struct font {name} = {{
	.height = {height},
	.glyph_count = ARRAY_SIZE(glyphs),
	.glyphs = glyphs,
	.bitmaps = bitmaps,
}};
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("ttf", type=Path, help="TrueType or OpenType font file")
    parser.add_argument("size", type=int, help="Font size in pixels")
    parser.add_argument("name", help="Name of the generated struct font symbol")
    parser.add_argument("output", type=Path, help="C file to write")
    parser.add_argument("--charset", default=DEFAULT_CHARSET, help="Characters to include")
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(args.ttf, args.size, args.name, args.charset))


if __name__ == "__main__":
    main()
