#!/usr/bin/env python3
"""Convert a picture into a 1 bpp struct canvas_bitmap, dithered for e-paper.

CMake runs this script on assets/picture.png at build time. The host tool
tools/convert/convert.py imports load_gray() and to_ink(), so that the firmware
and the host tools share one conversion.
"""

import argparse
from pathlib import Path

from PIL import Image, ImageChops, ImageOps

BYTES_PER_LINE = 12


def load_gray(path):
    """Return the picture as an upright mode "L" image on a white background."""
    # Cameras store a portrait shot sideways and record the rotation in EXIF.
    image = ImageOps.exif_transpose(Image.open(path)).convert("RGBA")
    # Transparent areas show as paper white.
    background = Image.new("RGBA", image.size, "white")
    return Image.alpha_composite(background, image).convert("L")


def to_ink(gray, dither=Image.Dither.FLOYDSTEINBERG):
    """Return a mode "1" image where a set pixel is black ink."""
    # Mode "1" of Pillow sets a bit for white, the opposite of struct canvas_bitmap.
    return ImageChops.invert(gray.convert("1", dither=dither))


def load_ink(path, max_width, max_height):
    gray = load_gray(path)

    if max_width and max_height:
        gray.thumbnail((max_width, max_height), Image.Resampling.LANCZOS)

    return to_ink(gray)


def format_bytes(data):
    lines = []
    for start in range(0, len(data), BYTES_PER_LINE):
        chunk = data[start : start + BYTES_PER_LINE]
        lines.append("\t" + " ".join(f"0x{byte:02x}," for byte in chunk))
    return "\n".join(lines)


def generate(source, ink, name):
    return f"""/*
 * Generated by scripts/img2c.py from {source.name}.
 * Do not edit by hand, regenerate instead.
 */

#include "picture.h"

static const uint8_t {name}_data[] = {{
{format_bytes(ink.tobytes())}
}};

const struct canvas_bitmap {name} = {{
	.width = {ink.width},
	.height = {ink.height},
	.data = {name}_data,
}};
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("source", type=Path, help="Picture in any format Pillow reads")
    parser.add_argument("output", type=Path, help="C file to write")
    parser.add_argument("--name", required=True, help="Name of the generated symbol")
    parser.add_argument("--max-width", type=int, help="Shrink to fit this width")
    parser.add_argument("--max-height", type=int, help="Shrink to fit this height")
    args = parser.parse_args()

    ink = load_ink(args.source, args.max_width, args.max_height)
    args.output.write_text(generate(args.source, ink, args.name))


if __name__ == "__main__":
    main()
