/*
 * Bitmap font tables generated by scripts/font2c.py.
 */

#ifndef FONT_H_
#define FONT_H_

#include <stdint.h>

struct font_glyph {
	/* Unicode code point, Basic Multilingual Plane only. */
	uint16_t codepoint;
	/* Horizontal advance in pixels, which is also the bitmap width. */
	uint8_t advance;
	/* Offset of the glyph bitmap in font.bitmaps. */
	uint32_t offset;
};

struct font {
	/* Line height in pixels, which is also the height of every bitmap. */
	uint8_t height;
	uint16_t glyph_count;
	/* Sorted by code point. */
	const struct font_glyph *glyphs;
	/* 1 bpp, MSB first, rows padded to a byte, a set bit is ink. */
	const uint8_t *bitmaps;
};

extern const struct font font_title;
extern const struct font font_body;

#endif /* FONT_H_ */
